#!/usr/bin/env sh
tplt query \
    -d NAME="$(git config --get user.name)" \
    -d EMAIL="$(git config --get user.email)" \
    -q DESCRIPTION="Project description"
    -q PROJECT_NAME="Project Name"

tplt replace
